<?php
/*
	Game siêu thị bạn bè được phát triển bởi GoHooH.CoM
	Vui lòng giữ bản quyền Việt hóa của GoHooH.Com
	Cám ơn bạn đã sử dụng sản phẩm của GoHooH.CoM
*/
$_SGLOBAL['comlang'] = array(
	'no_admin_permission'		=> 'Chỉ có quản trị viên mới vào được trang này',
	'update_successful'			=> 'Cập nhật thành công',
	'buyslave_notice'			=> 'Thông báo',
	'email_slave_subject'		=> 'Bạn đã bị \\1 mua',
	'memail_slave_message'		=> "\\1 xin chào\n\nBạn đã bị mua trong game Siêu thị Goer bởi \\2",
	'email_slave_message'		=> "\\1 xin chào\n\nBạn đã bị mua trong game Siêu thị Goer bởi \\2 n\nĐịa chỉ để vào siêu thị Goer \\3",
	'no_avatar'					=> 'Bạn cần up avatar và hoàn thành thông tin cá nhân để tham gia siêu thị Goer. <a href=cp.php>Click vào đây để bắt đầu</a>',
	'invite_success'			=> "Bạn đã mời \\1 thành công tham gia game Siêu thị Goer để  mua \\2",
	'invite_success_limit_pday' => "Bạn đã mời \\1 thành công tham gia game Siêu thị Goer nhưng bạn đã vượt quá số lượng bạn bè trong ngày nên không được tặng tiền.",
	'invite_success_limit_total'=> "Bạn đã mời \\1 thành công tham gia game Siêu thị Goer nhưng bạn đã vượt quá số lượng bạn bè trong ngày nên không được tặng tiền.",
	'invite_illegal'			=> "Hệ thống tìm thấy \\1 gian lận để mời \\2 bằng cách bán \\3",
	'invite_illegal_subject'	=> "Gian lận trong Siêu thị Goer",
	'all_category'				=> 'Tất cả',
	'money'						=> 'Tiền',
	'education'					=> 'Học vấn',
	'experience'				=> 'Exp',
	'health'					=> 'Sức khỏe',
	'loyalty'					=> 'Trung thành',
	'mood'						=> 'Tâm trạng',
	'slave_srunawaymsg'			=> '\\1 không thể bắt \\2 làm việc quá sức',
	'slave_mrunawaymsg'			=> '\\1 không thể bắt \\2 làm việc quá sức. Bạn nên cho họ nghỉ ngơi nhiều hơn',
	'cash_not_enough'			=> 'Bạn không đủ tiền để mua \\1 Bạn có thể <a href=\\2>mời bạn bè</a> tham gia Siêu thị Goer để có thêm \\3 Gyn.',
	'daily_limit_error'			=> "Hoạt động này chỉ được thực hiện \\1 lần trong ngày. Hãy trở lại vào ngày mai.",
	'action_limit_error'		=> "Trong \\1 giờ, chỉ có thể thực hiện \\2 công việc.",
	'activation_success'		=> 'Bạn đã kích hoạt thành công game Siêu thị Goer',
	'bought_successful'			=> 'Mua thành công',
	'bouhgtmsg_slave'			=> "\\1 lần \\2 đồng \\3 mua cho \\1 nhận được \\4 ",
	'bouhgtmsg_oldmaster'		=> "\\1 mua Goer \\2 của \\3 trong giao dịch \\4 Gyn",
	'bouhgtmsg_newmaster'		=> "\\1 mua \\2",
	'release_mastermsg'			=> "\\1 phát hành \\2 được \\3 Gyn",
	'release_slavemsg'			=> "\\1 trả tự do cho \\2 ",
	'release_error'				=> "Rất tiếc, bạn chua mua \\1 nên không thể thực hiện hoạt động.",
	'collect_msg'				=> "\\1 thuộc bộ sưu tập của \\2",
	'collect_error'				=> "\\1 đã thuộc bộ sưu tập của bạn.",
	'removecollect_msg'			=> "\\1 hủy bỏ bộ sưu tập \\2",
	'removecollect_error'		=> "Bạn chưa dưa \\1 vào bộ sưu tập",
	'discount_msg'				=> "\\1 để \\2 chục \\3 xử lý gấp \\2 trị giá \\4",
	'millionaire_master_msg'	=> "Xin chúc mừng, tài sản của bạn hơn \\1 và bạn đã trở thành Goer giàu có nhất. Không ai có thể mua bạn.",
	'millionaire_slave_msg'		=> "Goer \\1  mà bạn đã mua trở thành người giàu có nhất nên đã được giải phóng.",
	'millionaire_reject'		=> "Bạn không thể mua \\1",
	'buy_master_error'			=> "\\1 là chủ của bạn, bạn không thể mua Goer này",
	'changenick_successful'		=> "Thực thi cá nhân Goer bị mua thành công",
	'changeabout_successful'	=> "Bạn đã chỉnh sửa ghi chú cá nhận",
	'changenick_error'			=> "\1 không phải là Goer mà bạn mua nên không thể thực hiện hoạt động.",
	'me'						=> "Tôi",
	'you'						=> "Bạn",
	'maxslave_error'			=> "Số Goer được phép mua tối đa là \\1",
	'maxslave_perday_limit'		=> "Số Goer được phép mua tối đa trong ngày là \\1 ",
	'maxslave_discount_limit'	=> "Số Goer tối đa giảm giá là \\1",
	'slave_discount_minimum'	=> "Không thể sử dụng giá trị ít hơn \\1",
	'license_error'				=> 'Bạn không có quyền sử dụng plugins này, vui lòng vào http://www.gohooh.com/foum để được trợ giúp',
	'credit_err' => '������һ���������������',
	'tradenum_round_err'        => "����������Ϊ������",
'credit_round_err' => '������\\1 ��������',
'xianjin_successful' => '�һ��ֽ�ɹ���',
'jifen_successful' => '�һ����ֳɹ���',
'bouhgtmsg_ransom' =>'\\1  ���� \\3 �� \\2 �ĺ����������������\\2 �ڽ�����׬�� \\4 ��',
'ransom_not_enough'	=>'�Բ����������ֽ�������<br><br>[�����۸�:\\1   �����ֽ�:\\2 ]<br><br><font color=red>��ܰ��ʾ��</font>������<a href=\\4>��������</a>�μӡ�ū����������Ϸ���ɹ�����һλ����������� \\5 �����ھ�<a href=\\4>��������������</a>�ɣ�',
'ransom_perday_limit' =>'�Բ���ū��������һ��Ȳ����ڱ������������������� \\1 �ɣ�',	
'ransom_successful' => '�ܲ�����ѽ������������ˣ�',
'ransom_oldmaster' => '\\1 �������ﻨ�� \\2 ����Լ�( \\3 )�����ڽ�����׬�� \\4��',
'friend_err' => '��Ǹ��\\1 �����˽����Ѳ������������޷���δ�ӶԷ����ѵ�����¹���Է�Ϊū����<br>��������TaΪ���ѣ�Ȼ���ټ����ղŵĲ�����',
);

?>